### ISSUE TITLE
Compatible with Enterprise Accounts

### ISSUE THREAD

**Issue by jacksonrdlc** [manosim/gitify#141]
Is this currently compatible with Enterprise Accounts?

**Comment by ekonstantinidis** [comment]
Hello @jacksonrdlc! Currently gitify does not support Enterprise accounts. It is a nice feature to have though so I will add it to the list!

**Comment by ekonstantinidis** [comment]
@jacksonrdlc: Just got access to a GitHub Enterprise account (thank you GitHub) so hope to have something soon!

**Comment by amcedwards** [comment]
+1

**Comment by marcellodesales** [comment]
@ekonstantinidis Could you shed some lights here? I'm planning to start with the following:

1. Change the App ID/Secret

https://github.com/ekonstantinidis/gitify/blob/master/src/js/components/login.js#L24-L25

2. Change the hostname in the host

https://github.com/ekonstantinidis/gitify/blob/master/src/js/components/login.js#L38

Is there anything else hard-coded in terms of github api/connectivity?

thanks

**Comment by ekonstantinidis** [comment]
@marcellodesales Yes your plan sounds right! Unfortunately I cannot setup a machine to run GitHub Enterprise locally (GitHub provided me with a license but..). I would be more than happy to help with it so ping me if you need any help!

**Comment by marcellodesales** [comment]
@ekonstantinidis Ok sounds good... Let me try to build locally and test with out GHE instance and report back with a PR...  Thanks!

**Comment by marcellodesales** [comment]
@amcedwards @jacksonrdlc  @ekonstantinidis Here's what I got...

Config
-----

I'm proposing the use of the following config, which is compatible with different versions of APIs and hosts:

```js
module.exports = {
  github: {
    proto: "https",
    host: "github.intuit.com",
    apiVersion: "v3",
    auth: {
      clientId: "5c3891a38cd03ea8c8a6",
      clientSecret: "532d1c443b64dc40ae4921c5ec7a5adcafa9bf46"
    }
  },
  hostUrl: function getHostUrl() {
    return this.github.proto + "://" + this.github.host;
  },
  apiUrl: function getApiUrl() {
    return this.hostUrl() + "/api/" + this.github.apiVersion;
  }
};
```

Setup
-----

Just configured a new application. Since I did not see any callback, I just set the callback and host to the GHE host itself.

<img width="1004" alt="screen shot 2016-01-30 at 2 32 21 pm" src="https://cloud.githubusercontent.com/assets/131457/12698895/5bfa6136-c75e-11e5-8c3f-423625094acc.png">

Experience
------

We use LDAP to login to our GHE. The flow is the following:

* The first screen showed the login screen for the username and password.
* The Oauth2 authorization page is displayed.

<img width="798" alt="screen shot 2016-01-30 at 2 27 57 pm" src="https://cloud.githubusercontent.com/assets/131457/12698907/fbd33bb0-c75e-11e5-85cd-8df1dd5af168.png">

* The app is loaded and the window is closed. The notification was displayed properly.

<img width="610" alt="screen shot 2016-01-30 at 2 29 34 pm" src="https://cloud.githubusercontent.com/assets/131457/12698912/110365a0-c75f-11e5-9f40-5a69188f1418.png">

Proposal
-----

* Login options: Display the button with Login as is, and a link to the settings to login to GHE instance?

* Settings screen: Should the settings screen expose the configuration of the GHE to be used? Or should it be built only by whoever is distributing the Gitify? Say, the tools team of a company? This is to avoid multiple people creating appClients/appSecrets.

* Icon: I think we should have a different icon for the GHE version, so that we can have both the public GH and the private GHE apps opened.

I'm sending the PR with what I got and will be waiting on feedback...

**Comment by marcellodesales** [comment]
@ekonstantinidis how can I clear the local cache during development?

**Comment by ekonstantinidis** [comment]
@marcellodesales That looks really nice! About the user agent error - it should be fine. We can't set the user agent like that so I will have to remove that header at some point.

About your question: In `main.js`, inside the `initWindow()` function, you can use: 

    appIcon.window.openDevTools(true);

Also I would suggest to resize the window. Example below:

    function initWindow () {
      var defaults = {
        width: 800,
        height: 600,
        show: false,
        frame: false,
        resizable: true,
        webPreferences: {
          overlayScrollbars: true
        }
      };

      appIcon.window = new BrowserWindow(defaults);
      appIcon.positioner = new Positioner(appIcon.window);
      appIcon.window.loadURL('file://' + __dirname + '/index.html');
      appIcon.window.on('blur', hideWindow);
      appIcon.window.setVisibleOnAllWorkspaces(true);
      appIcon.window.openDevTools(true);

      initMenu();
      checkAutoUpdate(false);
    }

**Comment by marcellodesales** [comment]
@ekonstantinidis Thanks for reviewing this... This will come handy to monitor both the public and our Enterprise account... (That's the first page I access for both servers every day)...

So, this is my first time building a react app... I'm still having a hard time... will the browser-cache be cleared after I build the app? I'm trying to switch between the public github and the public, update the code, etc, and it looks like it stays in cache.

What can I do?

**Comment by marcellodesales** [comment]
@ekonstantinidis The commit 43f4bcf makes it compatible to the version on `master`. So, the next step now is to build the UI to expose out the settings for Which GitHub to listen to.

I'm thinking maybe we can add a view of multiple GitHub Instances. For instance, similar to `slack`, the different instances of GitHub Enteprise could be listed on the left-side, and the notifications listed as is...

<img width="67" alt="screen shot 2016-01-30 at 4 21 35 pm" src="https://cloud.githubusercontent.com/assets/131457/12699366/9641abf6-c76d-11e5-859a-ea6a334a85fb.png">

* GH: 
 * Name: Public GitHub
 * Icon: Main Icon from GH

For the instances of GHE
* GHE
 * Name: User-provided Name
 * Icon: Initials of the Name field or User-provided Icon

That would allow users to populate with their own settings. For instance, Users could use the DEV/QA hosts from the same company, or other instances.

**Comment by oligriffiths** [comment]
Hey, what's the status with this?

**Comment by marcellodesales** [comment]
@oligriffiths can you double-check the PR #149???

**Comment by manosim** [comment]
@marcellodesales Sorry for the long wait! Gitify had a major revamp since #149 was opened - moved to Redux and more.. I am currently working on V2 which has a big UI change (app moved from tray to a normal window and has a sidebar) that will give us some space to support GitHub Enterprise (will also support both Windows & Linux). Will let you know once the `v2` branch is stable enough!

**Comment by marcellodesales** [comment]
@manosim sounds good!!! Thanks for keep us posted!

**Comment by ProLoser** [comment]
Do people really use more than 1 enterprise Github at a time?

**Comment by Ustice** [comment]
@ProLoser Yes. I work for a client-services company, and I could potentially be moving back and forth between client projects. Some of them may have different GitHub enterprise accounts.

**Comment by aselamal** [comment]
any update on this?

**Comment by manosim** [comment]
Hi everyone, it's been quite a while since v2 which actually supported multiple enterprise accounts. I am closing this one as v3 is now out and this should still work. Let me know if it doesn't! 😄
