### ISSUE TITLE
Country availability

### ISSUE THREAD

**Issue by rgolea** [manosim/gitify#261]
Hi there! Is there a way we can have the app in different stores depending on the country? There are a lot of people loving this app (including me) and would like to have it in Europe, China, etc. Is there a way we can have this in the different countries? 
I'm grouping here the various issues regarding this and the countries mentioned:
Europe (Belarus) #260 
Asia (China) #258
Europe (Czech Republic) #256 
Europe (Spain) #261
Europe (UK) #261
Europe (Slovakia) #261
America (Canada) #261

Good job on the app man! Really nice!

**Comment by cedmax** [comment]
Please add UK to the list :)

**Comment by rgolea** [comment]
Done!

**Comment by scholtzm** [comment]
Not available in Slovakia either.

**Comment by Mackarous** [comment]
+🇨🇦

Any update on this?

**Comment by rgolea** [comment]
@Mackarous Right now I'm just updating the list as people add requests. I'm not sure @manosim is still active anymore.

**Comment by manosim** [comment]
Hi there! I am currently working on the version 2 of Gitify Desktop. Gitify mobile is not on the app store & google play store - you can [read more](https://github.com/manosim/gitify-mobile/issues/28) in the mobile app repository.

Since I need to renew my Apple Developer membership (otherwise Apple doesn't allow me to publish it) which costs about £79 per year - I was thinking to set it to cost £0.99. Let me know your thoughts!

Ps. People will always be able to build from source for free!

**Comment by rgolea** [comment]
@manosim if you publish it for 0.99 it would be great! This way we can contribute to the project.

Also, if you need any help with v2, leave a roadmap somewhere and ask for the community's help. I, for one, will be glad to help.

**Comment by manosim** [comment]
Thank you @rgolea! Here's a preview from v2! I would like to start cutting smaller releases so v2 might be out soon! Once it's out we can definitely set a new roadmap!
 
![image](https://cloud.githubusercontent.com/assets/6333409/23652416/c5006cc6-0320-11e7-9b27-540dca29921c.png)

**Comment by rgolea** [comment]
Are you using the new graphQL github api? It might help improve with speed and stuff.

**Comment by manosim** [comment]
Unfortunately they haven't released notifications support yet (unless I missed something)! Once they do, will definitely switch to the graphQL api 😄

**Comment by Mackarous** [comment]
@manosim not to start a whole thing in this issue, but would it be possible if clicking on the notification would go to the specific comment that's posted? Right now it just goes to the specific pull request

**Comment by manosim** [comment]
@rgolea & everyone the Gitify app is now available again on the App Store - I did set it to 99cents since I had to pay Apple for the developer account to republish it. Once i release v2 for the desktop app, I would like to add some more features to the app too!

@Mackarous There was a big conversation about this one  - Unfortunately in order to do that we need to make an extra request for each notification (so if you have 50 notifications that's 50 more requests) since the GitHub api does not return a link to the comment. I think once the Graph QL api is ready this would be a lot easier to implement!

**Comment by bobylito** [comment]
France 😎❤️🗼🇫🇷

**Comment by bradzacher** [comment]
I would love it if you could make it available in Australia 🇦🇺

**Comment by rgolea** [comment]
@bradzacher @bobylito I think it already is...

**Comment by bradzacher** [comment]
Just checked, and this is what I get when I open [the url on your home page](https://play.google.com/store/apps/details?id=com.gitify)

![image](https://cloud.githubusercontent.com/assets/7462525/23891996/f53b9d62-08ec-11e7-8d91-6a31a96e22ae.png)

**Comment by rgolea** [comment]
@bradzacher I don't think it's available for Android. Only iOS.
