### ISSUE TITLE
2FA not working on Safari on Mac

### ISSUE THREAD

**Issue by rachitmishra** [manosim/gitify#275]
The login window opens in Safari, and for some reason, the 2FA is not working. Time is in sync.
Can we switch to chrome based authentication/login page?

**Comment by deibeljc** [comment]
It uses chrome for me on my mac. Perhaps chrome is not your default browser?

**Comment by rachitmishra** [comment]
Sadly I am not able to use this app. the 2FA login never works.

**Comment by manosim** [comment]
Hello @rachitmishra! It would be very strange to open the page in safari. Gitify is built with electron which comes with Chrome bundled. When you click the login buton, it should open another chrome window. From [the code](https://github.com/manosim/gitify/blob/master/src/js/components/login.js#L25-L32), I don't see how it would open another browser. Can you send me some screenshots or a gif with happens when you click login? I will be happy to help you figure this out!

**Comment by rachitmishra** [comment]
@manosim indeed it is now opening in chrome but for some reason, neither the security codes nor the recovery code is working. anyways I am going ahead and closing the issue.
