### ISSUE TITLE
Notifications from private repo without organization owner permission

### ISSUE THREAD

**Issue by sepehr** [manosim/gitify#285]
The organization I'm working for has decided to not to provide any permissions to third-party apps. So I'm not able to grant permissions Gitify for that organization.

However, I get the notifications in my github account. I wonder, does github API provide a way to workaround this? The app just needs to read my account notifications.

_P.S. Thanks for developing such useful app :)_

**Comment by manosim** [comment]
Hello @sepehr! Thank you for your kind words! Unfortunately there is no workaround to override organisation permissions. When logging in, GitHub will ask for specific permissions and all that  [Gitify asks for](https://github.com/manosim/gitify/blob/41d2f6d63eb567366af58cf70ae4c7c29d610e75/src/js/utils/constants.js#L5) is access to two scopes: `['user:email', 'notifications']`.

As stated in the [GitHub API documentation](https://developer.github.com/v3/oauth/#scopes):
```
user:email - Grants read access to a user's email addresses.
notifications - Grants read access to a user's notifications.
```
Gitify does not ask for write permissions at all plus it is open source so unfortunately all I can do is  suggest asking the org admin again - maybe providing the above information.

### Another Option

Another option would be cloning Gitify and then you can [create your own OAuth GitHub App](https://github.com/settings/applications/new). All you have to do is [update the clientId and the client secret key](https://github.com/manosim/gitify/blob/41d2f6d63eb567366af58cf70ae4c7c29d610e75/src/js/utils/constants.js#L3-L4) and build the app. Then they will only have to trust you or the org admin can do this for you so that no one else would be able to change the scope's etc.

Hope the above make sense!

**Comment by sepehr** [comment]
Thank you so much @manosim :)

**Comment by Drjacky** [comment]
@manosim So, how this extension works?! [Notifier for GitHub](https://chrome.google.com/webstore/detail/notifier-for-github/lmjdlojahmbbcodnpecnjnmlddbkjhnn/)

Without sending an email to the owner and just with tokens which the user should handle it.
