### ISSUE TITLE
Add back dropdown from tray icon

### ISSUE THREAD

**Issue by AlecRust** [manosim/gitify#298]
Used to be one click to see the list of notifications right in the task bar, and be able to refresh from there too.

Now it's two clicks to open an app in the middle of the screen. When you click a notification the browser opens and Gitify becomes hidden behind (not in the <kbd>cmd</kbd>+<kbd>tab</kbd> list).

To me the main benefit of this app was it being fixed to the task bar. Can we have an option for this?

**Comment by rendhalver** [comment]
+1

**Comment by Mackarous** [comment]
I also wouldn't mind if clicking the menu bar just opened the new view instantly instead of having to then click open.

**Comment by JakeSidSmith** [comment]
It's nice to be able to position the new window, I think. The drop-downs in electron can be a little unpredictable.

Though I agree, a faster way to access the main window would be nice. I've currently got mine setup (using Better Touch Tool) so that it opens when I mouse into the top right corner... though that can get a little frustrating in itself.

**Comment by levithomason** [comment]
One click open, 👍
Show a window vs a dropdown, 👍
However, I don't think any settings nor menu are warranted here.

The menu only contains `Show Gitify` and `Quit`.  The only reason to click the icon is to show the app.  Once open, you can quit the app, <kbd>cmd</kbd> + <kbd>Q</kbd>.  There is then no need for any menu.

As for a setting, [Settings are Evil](https://www.youtube.com/watch?v=glZ1C-Yu5tw). **TL;DR** Rather than adding complexity and test cases, this could be solved by courage to make the right UX decision.  If anyone really wants a menu before opening the app, they'll forget and forgive you :)

**Comment by AlecRust** [comment]
> Settings are Evil

Agreed. Personally I would do away with the separate window and have it as a single-click dropdown as before. Anybody know the reason it was moved to a separate window?

**Comment by manosim** [comment]
Hello everyone and thank you for your feedback! It's much appreciated and I will be more than happy to do some further work! So there are few reasons that led me to move Gitify to a normal window.

> Support GitHub Enterprise

The new version has full support for GitHub Enterprise (even with multiple accounts). This could also be done in that small window next to the tray but I think everything would be squeezed, limiting any future additions.

> Support Windows & Linux

The current implementation (v2+) is literally one step away from supporting Windows & Linux too! In fact, I am pretty sure it would be an easy one. That is because of the new window and the tray functionality. The tray icon behaves in different ways in mac OS, Windows & Linux. The current implementation supports all 3 OSs at the same time.

> Regarding the normal app window (instead of the small tray window)

There was an ongoing issue with the position of the window on mac OS (and OSX). I think that Gitify would never be able to catch all cases of positioning. I've seen an app on the tray that groups other tray apps(if that makes sense?) and this breaks the positioning for some people. And that is only in mac OS - imagine what will happen once we land support for Windows & Linux too (tray on top, right, bottom, left etc).

### Thoughts

> Top Priority

Support Windows & Linux too. That means I would like not to revert everything (without meaning that there won't be changes).

> Tray Icon - **On click show Gitify instead of menu**

I think that this makes sense in OSX for everyone that prefers the tray icon instead of the dock one. Me personally, I now use the dock icon only so it looks like it doesn't affect people using the dock icon. I will give it a go **ASAP** - I think it shouldn't take too long (working full time so will try my best time wise).

> Gitify "Helper"

A great idea would be for Gitify to come along with a helper (much like 1Password). So you will have the normal app (proper window) and a helper in the tray which will use something like the old pre-v2 gitify. I think that will fit everyone's favour but obviously it is not an easy one.

> Suggestions

Looking forward to hear more ideas!

Thank you,
Manos.

**Comment by AlecRust** [comment]
Fair enough. I don't want to get in the way of cross-platform compatibility.

Part of my issue was:
> When you click a notification the browser opens and Gitify becomes hidden behind (not in the <kbd>cmd</kbd> + <kbd>tab</kbd> list).

This was down to having the "Tray icon" radio set in settings. Now I have it set to the default "Both icons" and Gitify does show in the in the <kbd>cmd</kbd> + <kbd>tab</kbd> list. However if you close the window it's still there in the list, and if you <kbd>cmd</kbd> + <kbd>Q</kbd> it the task bar icon is removed too 🙂 

To me the macOS experience has taken a hit here in favour of cross-platform compatibility. It sounds like a 1Password-like helper would solve the problem, as long as it didn't require the main app to be open.

> I've seen an app on the tray that groups other tray apps

Yes I use [Bartender](https://www.macbartender.com/) for managing my task bar icons. I'd happily leave it alone in the main task bar rather than collapsing it though if it meant I could view notifications from my task bar again 🙂  I notice 1Password's dropdown task bar helper works fine when handled by Bartender or not, but I understand this is no easy feat/not Electron.

**Comment by manosim** [comment]
Thank you for your reply @AlecRust! I think that #300 solves the issue with the tray icon. Also I've made it so that if you click on a native notification and it opens the browser, it will hide the Gitify window to prevent having multiple windows open.

> Using the Dock icon (or "Both")

It looks like when you use the dock icon, Gitify will show up in the <kbd>cmd</kbd>+<kbd>tab</kbd> list. So if you only use the tray icon, that won't be a problem.

I guess that 1Password is a native app so that would be why it doesn't have these issues. I will release 2.0.2 with #300 soon(hopefully tomorrow) and l think this will improve the user experience a lot. Let's see how it goes!

**Comment by manosim** [comment]
Update! I managed to release 2.0.2 (just now) which changes the behaviour of the tray icon, it now toggles the visibility of gitify. Hope that this improves the UX!

**Comment by JakeSidSmith** [comment]
![nice](http://i2.kym-cdn.com/photos/images/newsfeed/000/450/154/820.jpeg)

**Comment by aioue** [comment]
Politely expressing my desire for the window to hide when out of focus - like the last version.

Very much liked the 'drawer' type drop down - have enough windows on exposé!

Would like to be able an option to click back on my editor window and have gitify disappear, without the additional toggle-off click.

**Comment by FezVrasta** [comment]
To me it looks too invasive the new version. I liked this app because it was out of my way and easily reachable.

Gonna use the old version until the old behavior has been restored.

**Comment by FezVrasta** [comment]
Any news on this? Sorry but it's really breaking the workflow of a lot of people.

At least release the old version with the auto updates disabled?

**Comment by bretonics** [comment]
I would love to see this feature back! It really does take away from what Gitify used to be intended for, an inconspicuous notifications menu bar app. Any update??

**Comment by manosim** [comment]
It's been quite a while since this was first discussed but **Gitify v3 is now out** and the app is back to being a menu bar app - back to the original plan! Hope that's for the best 😄
