### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by pgoodjohn** [manosim/gitify#349]
Hi everyone.

I've been using this project for years but a couple of weeks ago the fetching stopped working. I was wondering if it was still an active project with someone behind it.

If that is not the case I am willing to help out, my JS skills are not that great but I think I know enough to make it work.

**Comment by xcambar** [comment]
I'd love to hear about the status of the project as well.
And offer some help if it is still active, too.

**Comment by JakeSidSmith** [comment]
Hey, @pgoodjohn. What do you mean by:

> the fetching stopped working

It is no longer getting notifications?

Mine is still functioning fine. Have you perhaps revoked access / deleted the token?

You can press CMD + ALT + I to open the inspector and see why the requests are failing.

**Comment by pgoodjohn** [comment]
Hey @JakeSidSmith!
Totally forgot about this issue. My organisation had revoked access to Gitify hence why I wasn't getting any more notification.
Everything worked fine again after re-enabling it.

**Comment by JakeSidSmith** [comment]
Okay, glad it's sorted.

As for the status of this repo... I'm not sure. I used to work with @manosim, and helped with a few small things in Gitify, but he's since moved companies and we haven't spoken in a while.

**Comment by rdohms** [comment]
Indeed, would love to see if we can get more people involved at least in helping merge PRs and getting more contributors.

**Comment by xcambar** [comment]
FWIW, I would really love to get things moving around this project so I took the initiative to fork the repository to https://github.com/Two15/gitify and from now on, I am planning to welcome any contribution and get the project back on.

As a first proposition, I'd like to discuss its governance, as I want this fork to be as open as possible and help the community shine. See https://github.com/Two15/gitify/issues/1 for details.

FWIW, the organization `gitify` already exists in github, that's why I forked it to another org I own.

I really hope you'll welcome the initiative and join in making gitify even greater and more helpful than it is now. @manosim thanks for all the hard work, you seem to have moved on to new projects now, which is perfectly understandable. Should you wish to contribute on the new fork or get this very repo back on track, you have everything in hand and the people behind to help you. I wish you all the best, should you not respond.

**Comment by manosim** [comment]
Hi everyone, Gitify recently went though a major rewrite - moved to TS, updated Electron, updated all dependencies, moved back to the "original tray icon" app and more(see [release notes](https://github.com/manosim/gitify/releases/tag/v3.0.0)). I am trying to automate everything as much as possible to prevent holding back new releases - soon all releases will be made through GitHub Actions (or Circle CI). Hope that's good news for everyone!

@pgoodjohn let me know if you still have the same issue with fetching (using the latest version) and I am happy to reopen this issue.
