### ISSUE TITLE
Cannot open without security exception

### ISSUE THREAD

**Issue by itskingori** [manosim/gitify#388]
Just doing as instructed 😅 ... wondering if this is something that can be addressed (no idea how macOS development works):

<img width="532" alt="Screenshot 2020-03-04 at 13 41 06" src="https://user-images.githubusercontent.com/703786/75871601-de02a800-5e1d-11ea-86cc-1f3525e4e864.png">

<img width="780" alt="Screenshot 2020-03-04 at 13 42 19" src="https://user-images.githubusercontent.com/703786/75871714-0be7ec80-5e1e-11ea-8631-26cf0f56a9b0.png">

**Comment by JakeSidSmith** [comment]
If you right click and select open you should then get a prompt that allows you to open the app. After you've done this once you'll be able to open Gitify without issues.

**Comment by itskingori** [comment]
Yes, that's what I did. Just wondering if there's a way to not have to do this. Shared this with a bunch of people who do not want to install the app because it's "not secure" (which I understand is not necessarily the case.

**Comment by zacblazic** [comment]
I'd really like to see this resolved. I'm sure there are a few people that are hesitating to use this application due to the perceived lack of authenticity.

Perhaps the fact that you need to enroll in the Apple Developer Program which charges an annual fee may be a blocker?

See: 
* https://www.electronjs.org/docs/tutorial/code-signing
* https://developer.apple.com/developer-id/

**Comment by manosim** [comment]
Hi everyone, this should be fixed in the next release. The app was already signed with a certificate from the Apple developer portal as it should be. The step I was missing, was the notarization of the app which is required since macOS 10.14.5 - you can read more in this [great article](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/).

Once 3.0.2 is out, no users should get that scary warning 😄

**Comment by Luflosi** [comment]
I recommend reading [The true and false security benefits of Mac app notarization](https://lapcatsoftware.com/articles/notarization.html) and [Revisited: The true and false security benefits of Mac app notarization](https://lapcatsoftware.com/articles/notarization2.html), it was a very interesting to read.
Now, since you are already enrolled in the Apple Developer Program, adding notarization to make the scary warning go away was probably worthwhile for the peace of mind of some users, even if there are no real security benefits.
